//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyntaxTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SyntaxTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to học sinh học danh_từ MEAN
        ///học sinh vật cảnh danh_từ MEAN
        ///phần mềm máy danh_từ MEAN
        ///phần mềm danh_từ MEAN
        ///học sinh danh_từ MEAN
        ///con đường danh_từ MEAN
        ///đi học động_từ MEAN
        ///a dua động_từ MEAN
        ///a hoàn danh_từ MEAN
        ///a phiến danh_từ MEAN
        ///a tòng động_từ MEAN
        ///ai đại_từ MEAN
        ///ai ai  MEAN
        ///ai điếu danh_từ MEAN
        ///ai oán tính_từ MEAN
        ///am danh_từ MEAN
        ///am hiểu động_từ MEAN
        ///am pe danh_từ MEAN
        ///an tính_từ MEAN
        ///an ba ni danh_từ MEAN
        ///an bài động_từ MEAN
        ///an cư động_từ MEAN
        ///an dưỡng động_từ MEAN
        ///an nghỉ động_từ  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dictA {
            get {
                return ResourceManager.GetString("dictA", resourceCulture);
            }
        }
    }
}
